# Base configs
baseurl: "https://squibyu.github.io/portfolio"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Artwork by James Yu"
subtitle: "Attic"
author: "James Yu"
header:
 title: "Artwork"
 subtitle: "by James Yu"
footer:
 name: "James Yu"
 bio: "Bio placeholder"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
# exif: '[{"tag": "Name", "icon": "dot-circle-o"}]'
social_urls:
  e-mail: "jinxuanyu26@gmail.com"
  instagram: "https://www.instagram.com/squib.yu"
